// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	KV: KVNamespace;
	RESEND_API_KEY: string;
	OPENAI_API_KEY: string;
	GOOGLE_GENERATIVE_AI_API_KEY: string;
	CLERK_SECRET_KEY: string;
	SIGNING_SECRET: string;
	DB: D1Database;
}
